### ISSUE TITLE
increment gem version

### ISSUE THREAD

**Issue by dylnclrk** [darthdeus/flat-ui-rails#10]
increment gem version to make sure that updates are pushed out

**Comment by darthdeus** [comment]
Afaik last changes were coming with a version increment in 36f0442.

**Comment by dylnclrk** [comment]
Woah! This must have been one of my earliest comments on Github. I'm sorry for sounding so rude. Thank you!

**Comment by darthdeus** [comment]
hehe no problem :) I've been neglecting this repo anyway. I haven't touched Ruby in many years.
