### ISSUE TITLE
can't style checkbox with flat-ui-rails

### ISSUE THREAD

**Issue by pavankat** [darthdeus/flat-ui-rails#14]
putting this inside a checkbox: 

data-toggle="checkbox" doesn't style checkbox with flat-ui-rails.

Also using $(':checkbox').checkbox();
in the javascript of the page doesn't either.

**Comment by darthdeus** [comment]
This repo only packages Flat UI, for issues other than how it integrates with the Rails asset pipeline please post an issue in the official Flat UI repository at https://github.com/designmodo/Flat-UI.
