### ISSUE TITLE
Mobile dropdown list  display issue 

### ISSUE THREAD

**Issue by itayariely** [darthdeus/flat-ui-rails#15]
the max-heigth of the dropdown is 244px, when it showes on pc scroller appears, but in mobile view it cut the box and I cant see or chose the options.
So how can I change the maximum heigth or in mobile use the defult of the brwoser dropdown?
Thanks

**Comment by darthdeus** [comment]
This gem only bundles Flat UI for the Rails asset pipeline. I'm not the developer of Flat UI, so I can't really answer questions regarding how it works.
