### ISSUE TITLE
Will this override default bootstrap behavior if you already have twitter-bootstrap-rails

### ISSUE THREAD

**Issue by akshatpradhan** [darthdeus/flat-ui-rails#6]
I'm using this gem
https://github.com/seyhunak/twitter-bootstrap-rails

On this repo, 
https://github.com/akshatpradhan/spoutlets

and I'd like to know if there would be any complications if both gem `flat-ui-rails` and `twitter-bootstrap-rails` were both installed together.

**Comment by darthdeus** [comment]
I'm closing this since it's not an actual issue with this repo, but rather a problem of how bootstrap and flat-ui interact together.
